export const APP_FEATURES = [
  {
    id: "01",
    title: "Tailored Just for You",
    description:
      "Get interview questions and model answers based on your role, experience, and specific focus areas – no fluff, just relevance.",
  },
  {
    id: "02",
    title: "Learn at Your Own Pace",
    description:
      "Expand answers only when you're ready. Dive deeper into any concept instantly with AI-powered detailed explanations.",
  },
  {
    id: "03",
    title: "Capture Your Insights",
    description:
      "Add personal notes to any question and pin important ones to the top – making your learning more organized.",
  },
  {
    id: "04",
    title: "Understand the 'Why' Behind Answers",
    description:
      "Beyond just answers – unlock detailed concept explanations generated by AI, helping you truly master each topic.",
  },
  {
    id: "05",
    title: "Smart Bookmarking",
    description:
      "Save your favorite or most difficult questions to revisit later, grouped intelligently by topics and skills.",
  },
  {
    id: "06",
    title: "Real-Time Hints",
    description:
      "Get contextual hints and links to official documentation, blog posts, or videos as you explore each topic.",
  },
  {
    id: "07",
    title: "Daily Interview Drills",
    description:
      "Receive a personalized set of 5–10 questions daily to keep your interview prep consistent and sharp.",
  },
  {
    id: "08",
    title: "Track Your Progress",
    description:
      "Monitor how much you've learned, what’s pending, and areas needing improvement with visual progress tracking.",
  },
  {
    id: "09",
    title: "AI-Powered Practice Mode",
    description:
      "Simulate a real interview with AI asking questions and evaluating your answers with personalized feedback.",
  },
  {
    id: "10",
    title: "Explore Topic Maps",
    description:
      "Navigate through a visual roadmap of tech topics connected to each question – from basics to advanced patterns.",
  },
];
//export default APP_FEATURES;